package com.sample.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.sample.util.UserStatus;
import lombok.*;

import java.util.Date;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "user")
public class User {

    @DynamoDBHashKey
//    @DynamoDBIndexHashKey(globalSecondaryIndexNames = {FIRST_NAME})
    private String hashKey;

    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    private String rangeKey;

    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "firstName-index")
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "phone-index")
    private String phone;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "email-index")
    private String email;

    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.M)
    private Address address;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private UserStatus status;

    @DynamoDBAttribute
    private String searchKeys;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
    private Boolean isFirstLogin;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBTypeConvertedTimestamp(pattern = "dd-M-yyyy hh:mm:ss", timeZone = "GTM")
    private Date createdAt;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBTypeConvertedTimestamp(pattern = "yyyyMMddHHmmssSSS")
    private Date updatedAt;
}
